ta2: Done with initial updates. Adding and porting unit tests to new language spec.

diff --git a/cs354/ta2/test/run b/cs354/ta2/test/run
--- a/cs354/ta2/test/run
+++ b/cs354/ta2/test/run
@@ -37,17 +37,23 @@ Prgs() {
 
 # Name for test: ${1##*/} or ${t##*/}
 Compare() {
-    case $2 in
-	i) trans="Interpreter" && exp="exp" ;;
-	c) trans="Compiler" && exp="exp" ;;
-    s) trans="Scanner($3)" && exp="scan$3" ;;
-    esac
+    if [ $2 == i ] ; then
+        printf "[$3] Interpreter:\t"
+        exp="exp$3"
+    elif [ $2 == c ] ; then
+        printf "[$3] Compiler:\t\t"
+        exp="exp$3"
+    elif [ $2 == s ] ; then
+        printf "[$3] Scanner:\t\t"
+        exp="scan$3"
+    fi
+    
     if eval diff -q -w $1/$exp $1/out$3.$2 2>/dev/null ; then
-        printf "%s:\t%s \033[92;1mpassed\033[0m\n" $trans
+        printf "\033[92;1mpassed\033[0m\n"
         passed=$((passed+1))
         return 1
     else
-        printf "%s:\t%s \033[91;1mfailed\033[0m\n" $trans >&2
+        printf "\033[91;1mfailed\033[0m\n" >&2
         failed=$((failed+1))
     fi
 }
@@ -55,32 +61,44 @@ Compare() {
 # Iterate through each test directory
 for t in test-* ; do
     printf "\033[1m\t[ %s ]\033[0m\n" ${t##*/}
-
-    # Init input file if missing
-    [ -f $t/inp ] || > $t/inp
     
     # Scanner Test
     for p in $t/prg* ; do
         prgnum=$(PrgNum $p)
+
+        printf "\033[2;3m\t[ program $prgnum ]\033[0m\n"
+
         # If scanner test doesn't exist for program, skip.
         if [ -f $t/scan$prgnum ]; then
-            eval java -cp .. Scanner \""$(cat $p)"\" < $t/inp > $t/out$prgnum.s 2> $t/scanerrs
+            eval java -cp .. Scanner \""$(cat $p)"\" > $t/out$prgnum.s 2> $t/scanerrs$prgnum
             Compare $t s $prgnum
         else
-            printf "Scanner(%s):\t\033[2;3mskipped\033[0m\n" $prgnum
+            printf "[%s] Scanner:\t\033[2;3mskipped\033[0m\n" $prgnum
+            skipped=$((skipped+1))
+        fi
+
+        if [ -f $t/exp$prgnum ]; then
+
+            # Ensure input
+            [ -f $t/inp$prgnum ] || > $t/inp$prgnum
+
+            # Interpreter Test
+            export Code=$t/gen$prgnum
+            eval java -cp .. Main "$t/prg$prgnum" < $t/inp$prgnum > $t/out$prgnum.i 2> $t/generrs$prgnum
+            Compare $t i $prgnum
+
+            # Compiler Test
+            clang-format -i $Code.c
+            gcc -Wall $Code.c -o $Code 2>$t/gccerrs$prgnum && $Code < $t/inp$prgnum > $t/out$prgnum.c
+            Compare $t c $prgnum
+        else
+            printf "[%s] Interpreter:\t\033[2;3mskipped\033[0m\n" $prgnum
+            skipped=$((skipped+1))
+
+            printf "[%s] Compiler:\t\t\033[2;3mskipped\033[0m\n" $prgnum
             skipped=$((skipped+1))
         fi
     done
-
-    # Interpreter Test
-    export Code=$t/gen
-    eval java -cp .. Main "$(Prgs $t/prg*)" < $t/inp > $t/out.i 2> $t/generrs
-    Compare $t i
-
-    # Compiler Test
-    clang-format -i $Code.c
-    gcc -Wall $Code.c -o $Code 2>$t/gccerrs && $Code < $t/inp > $t/out.c
-    Compare $t c
 done
 
 # Print overall results of the testing
